version: "3.7"
services:
  redis626:
    image: "redis:6.2.6"
    ports:
      - "16379:6379"
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "23306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "bluebell"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./init.sql:/data/application/init.sql
  bluebell:
    build: .
    command: sh -c "/wait-for.sh redis626:6379 mysql8019:3306 -- ./bluebell ./conf/config.yaml"
    depends_on:
      - mysql8019
      - redis626
    ports:
      - "8082:8081"